### ISSUE TITLE
Figma design for landing page

### ISSUE THREAD

**Issue by harshita2216** [harshita2216/hello-jobs#1]
Explore Dribble and other resources to take inspiration for the UI.

**Comment by Shreyan-12345** [comment]
can you plz explain about this in detail?

**Comment by harshita2216** [comment]
> can you plz explain about this in detail?

Hi Shreyan. Since we'll be building this platform from scratch, we need to design the UI. Based on how we design, we'll be able to implement it on the website.

**Comment by asdsyd** [comment]
please assign me this issue.

**Comment by harshita2216** [comment]
> please assign me this issue.

Hey. You may share your design to me on discord. We'll go ahead with the one everyone likes. :)

**Comment by asdsyd** [comment]
> > please assign me this issue.
> 
> Hey. You may share your design to me on discord. We'll go ahead with the one everyone likes. :)

Alright okay.

**Comment by codervivek5** [comment]
I can make it very well.

**Comment by harshita2216** [comment]
> I am Interested in the project. can make it very well.

Sure, you can go ahead with this issue. We'll pick the design we all like the most.

**Comment by Ankit62042** [comment]
Hii, I Shared my UI Design on Discord Server :)

**Comment by prayushi25** [comment]
Hey! I would surely be making changes to the design that I have shared on discord and try to make it better!
