### ISSUE TITLE
Banner section

### ISSUE THREAD

**Issue by harshita2216** [harshita2216/hello-jobs#4]
![image](https://user-images.githubusercontent.com/65803563/151835782-62e0b32a-6442-4d5f-825d-64fb073de688.png)

1. The banner section includes everything except the header in this image. Use this image as a reference. You are free to tweak as you like. 
2. Responsive UI.

**Comment by 57alok** [comment]
I want to work on this issue under JWOC. Please assign me this

**Comment by 57alok** [comment]
I want to work on this issue under JWOC
Please assign me this @harshita2216

**Comment by harshita2216** [comment]
> I want to work on this issue under JWOC Please assign me this @harshita2216

Go ahead! All the best. 🥳

**Comment by nikhilesh-03** [comment]
mam i want to contribute in this project @harshita2216

**Comment by Sanghu01** [comment]
I want to contribute in this issue .

**Comment by 57alok** [comment]
This issue is completed @harshita2216 .Thank you for merging it.😊
