### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by ayush-sleeping** [harshita2216/hello-jobs#7]
As we know this project is going to start from the base, So we need a Good "Readme" for this awesome Project .
So, that anyone who want to contribute in this Project or visited this Repo.  can understand this Project clearly and get started.

**Comment by ayush-sleeping** [comment]
Hey @harshita2216 , I want to work on this issue under JWOC'22 .

**Comment by harshita2216** [comment]
Hey @ayush-sleeping. Please enlist the additions you're planning to make to the current readme?

**Comment by ayush-sleeping** [comment]
Hey Harshita , Give me time till 12 pm in the noon , I will show you the result and then if you suggest me to add more things which you like , I will add those things also ....

**Comment by harshita2216** [comment]
> Hey Harshita , Give me time till 12 pm in the noon , I will show you the result and then if you suggest me to add more things which you like , I will add those things also .... and will make a Impressive Readme for this awesome Project.

Yeah sure. Go ahead. All the best! 🚀

**Comment by ayush-sleeping** [comment]
Hey @harshita2216  , Kindly visit https://github.com/ayush-sleeping/hello-jobs , 
and tell me , What do you think about New Readme

**Comment by ronitblenz** [comment]
Hey @harshita2216 I can design interactive and nice README file. check my profile at https://github.com/ronitblenz 
I will be happy to be assigned

**Comment by harshita2216** [comment]
> Hey @harshita2216 I can design interactive and nice README file. check my profile at https://github.com/ronitblenz I will be happy to be assigned

Since it is already assigned and is being worked on, I will not be able to assign it to you at this moment. Although if you feel there could be more additions, feel free to create another issue and work on the same once his PR gets merged. :)

**Comment by ayush-sleeping** [comment]
hey @harshita2216 , If you will add a Licence and Code of conduct ,
Then I will update it to the Readme , What do you think ,

Or you want , then will push a PR now
